# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ValetFixChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ValetFixChat
  pod 'SVProgressHUD'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/RemoteConfig'
  pod 'FirebaseUI'
  pod 'AccountKit'
  pod 'MessageKit'
  pod 'MessageInputBar'
  pod 'AMPopTip'
  pod 'RecordButton'

  target 'ValetFixChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
